import os
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Define la ruta de la carpeta para la retroalimentación
carpeta_retroalimentacion = 'retroalimentacion'

# Asegúrate de que la carpeta exista; si no, créala
if not os.path.exists(carpeta_retroalimentacion):
    os.makedirs(carpeta_retroalimentacion)

# Definir las preguntas y respuestas de muestra
preguntas = [
   
   
  
   
 
 
    
    "¿Tienes interés en aprender sobre programación de software?",
 "¿Disfrutas resolviendo problemas lógicos y matemáticos?",
 "¿Te gustaría trabajar con tecnologías de la información y la comunicación?",
 "¿Eres curioso acerca de cómo funcionan las computadoras y los sistemas informáticos?",
 "¿Te sientes cómodo trabajando con equipos y colaborando en proyectos técnicos?",
 "¿Disfrutas explorando nuevas tecnologías y aplicaciones informáticas?",
 "¿Tienes habilidades para el análisis y la resolución de problemas complejos?",
 "¿Eres bueno en identificar patrones y tendencias en grandes conjuntos de datos?",
 "¿Tienes paciencia para realizar pruebas y depurar programas informáticos?",
 "¿Te interesa el desarrollo de software para aplicaciones móviles?",
 "¿Eres hábil en el diseño y desarrollo de interfaces de usuario?",
 "¿Te gusta trabajar con sistemas operativos y redes de computadoras?",
 "¿Tienes habilidades para el trabajo en equipo y la comunicación efectiva?",
 "¿Te sientes atraído por la ciberseguridad y la protección de datos?",
 "¿Cuando se presenta algún problema en un sistema quieres ayudar?",
 "¿Sientes interés en el desarrollo y mantenimiento de Software?",
   "",
 "¿Disfrutas organizando y planificando actividades?",
"¿Te interesa el funcionamiento interno de las empresas?",
"¿Eres bueno/a gestionando recursos y presupuestos?",
"¿Te atrae la idea de liderar equipos y dirigir proyectos?",
"¿Te gusta analizar datos y usarlos para tomar decisiones?",
"¿Crees en la importancia de la comunicación efectiva en un entorno laboral?",
"¿Te resulta interesante aprender sobre estrategias de negocios y marketing?",
"¿Tienes facilidad para adaptarte a diferentes situaciones en un entorno laboral?",
"¿Te consideras una persona orientada a resultados?",
"¿Eres capaz de manejar múltiples tareas y prioridades simultáneamente?",
"¿Consideras importante mantener un equilibrio entre los objetivos de la empresa y el bienestar de los empleados?",
"¿Te sientes cómodo/a resolviendo conflictos dentro de un equipo?",
"¿Crees en la importancia de la ética en el mundo empresarial?",
"¿Disfrutas enfrentando desafíos y encontrando soluciones creativas?",
"¿Te interesan los aspectos legales y regulatorios relacionados con las empresas?",
"¿Estarías dispuesto/a a asumir responsabilidades adicionales para el éxito de un proyecto?",
    "",

"¿Disfrutas resolviendo problemas matemáticos y de física aplicada?",
"¿Te interesan los diseños y la planificación de estructuras y edificios?",
"¿Eres meticuloso/a y cuidadoso/a con los detalles en tu trabajo?",
"¿Te sientes atraído/a por el desarrollo y la construcción de infraestructuras importantes?",
"¿Te gusta trabajar en proyectos a largo plazo que requieren persistencia y dedicación?",
"¿Tienes habilidades para comprender y aplicar principios de mecánica y resistencia de materiales?",
"¿Te sientes cómodo/a utilizando software de diseño y modelado en 3D?",
"¿Eres capaz de trabajar eficientemente en equipos multidisciplinarios?",
"¿Tienes interés en aprender sobre normas y regulaciones de construcción y seguridad?",
"¿Consideras importante la implementación de prácticas sostenibles en proyectos de construcción?",
"¿Estarías dispuesto/a a trabajar en entornos de alta presión y plazos ajustados?",
"¿Te sientes cómodo realizando inspecciones en terreno y supervisando proyectos de construcción?",
"¿Te interesa aprender sobre los aspectos geotécnicos y de materiales en la construcción?",
"¿Te atrae la idea de trabajar en proyectos que impacten positivamente en la comunidad y el medio ambiente?",
"¿Te consideras una persona que disfruta aprendiendo sobre la ingeniería estructural y de materiales?",
    "¿conoces la ingenierio civil?",
    "",
"¿Te sientes atraído/a por la electrónica y la tecnología en general?",
"¿Disfrutas resolviendo problemas lógicos y trabajando con circuitos eléctricos?",
"¿Tienes interés en diseñar y construir dispositivos electrónicos?",
"¿Te gusta aprender sobre los últimos avances en la electrónica y la informática?",
"¿Eres meticuloso/a y cuidadoso/a con los detalles en tu trabajo?",
"¿Tienes habilidades para programar y desarrollar software relacionado con la electrónica?",
"¿Te sientes cómodo/a utilizando herramientas de medición y equipos de laboratorio?",
"¿Eres capaz de trabajar en equipos multidisciplinarios en proyectos de electrónica?",
"¿Te interesa la automatización y el control de sistemas electrónicos?",
"¿Tienes curiosidad por explorar la robótica y la inteligencia artificial?",
"¿Consideras importante la seguridad en el diseño de sistemas electrónicos?",
"¿Te sientes atraído/a por la electrónica aplicada a las comunicaciones?",
"¿Te interesa la investigación y el desarrollo de nuevas tecnologías electrónicas?",
"¿Eres una persona que disfruta aprendiendo sobre electrónica analógica y digital?",
"¿Te sientes cómodo/a solucionando problemas técnicos en dispositivos electrónicos?",
"¿Estarías dispuesto/a a trabajar en entornos de alta tecnología y constantemente cambiantes?",
   "",
"¿Te atrae la idea de gestionar eficientemente la cadena de suministro de una empresa?",
"¿Disfrutas resolviendo problemas logísticos y optimizando procesos?",
"¿Sientes interés por la tecnología y su aplicación en la gestión de la cadena de suministro?",
"¿Te gustaría aprender a reducir los costos operativos en una empresa?",
"¿Prefieres trabajar en la organización de la logística interna o en la logística de distribución?",
"¿Cómo te sentirías al enfrentar el desafío de gestionar el inventario de una empresa?",
"¿Te ves planificando rutas de transporte para optimizar la entrega de productos?",
"¿Te atrae la idea de administrar un almacén y asegurar que los productos estén disponibles cuando se necesiten?",
"¿Eres una persona que considera importante gestionar el riesgo en los negocios?",
"¿Te gustaría medir el rendimiento de una empresa utilizando indicadores clave de logística?",
"¿Sigues de cerca las tendencias tecnológicas en logística, como la automatización y la sostenibilidad?",
"¿Te gustaría trabajar en un entorno empresarial globalizado y entender cómo afecta la cadena de suministro?",
"¿Valoras la satisfacción del cliente como un indicador crucial del éxito empresarial?",
"¿Te consideras un buen tomador de decisiones y estás dispuesto a enfrentar desafíos en la logística?",
"¿Te interesa la logística inversa y la gestión de devoluciones de productos?",
"¿Consideras importante la ética y los aspectos sociales en la Ingeniería en Logística?"
  "",
"¿Disfruta trabajar con números y análisis financiero?",
"¿Te interesa aprender sobre leyes y regulaciones relacionadas con la contabilidad?",
"¿Eres organizado y te gusta llevar un registro detallado de información?",
"¿Te interesa la economía y cómo afecta a las empresas y personas?",
"¿Tienes habilidades para resolver problemas complejos y encontrar soluciones eficientes?",
"¿Te atrae la idea de asesorar a empresas en temas financieros y fiscales?",
"¿Disfrutas trabajar en equipo y colaborar con otros profesionales?",
"¿Te interesa investigar y analizar situaciones financieras para tomar decisiones?",
"¿Sientes curiosidad por la tecnología y cómo se aplica en la contabilidad moderna?",
"¿Te gustaría trabajar en auditorías para asegurar la precisión de los registros contables?",
"¿Eres bueno para comunicarte de manera clara y efectiva, tanto por escrito como verbalmente?",
"¿Te atrae la idea de trabajar en el sector público, en áreas como finanzas gubernamentales o auditoría estatal?",
"¿Te interesa la responsabilidad social empresarial y cómo la contabilidad puede contribuir a ella?",
"¿Te gustaría trabajar en consultoría financiera y asesorar a diferentes tipos de empresas?",
"¿Tienes interés en aprender sobre impuestos y cómo impactan en las finanzas personales y empresariales?",
"¿Te motiva la posibilidad de crecimiento profesional y de especialización en el campo de la contabilidad?"
 "",
"¿Te fascina la idea de trabajar con estructuras y materiales a una escala nanométrica?",
"¿Disfrutas resolviendo problemas complejos mediante el uso de la tecnología?",
"¿Tienes curiosidad por entender cómo las propiedades de los materiales cambian a nivel molecular?",
"¿Te atrae la idea de contribuir al avance de la ciencia y la tecnología a través de la investigación?",
"¿Sientes afinidad por las disciplinas de la física, la química y la biología?",
"¿Disfrutas diseñando y experimentando con dispositivos a una escala extremadamente pequeña?",
"¿Te interesa la posibilidad de desarrollar nuevas aplicaciones tecnológicas en campos como la medicina, la electrónica o la energía?",
"¿Eres meticuloso/a y te gusta prestar atención a los detalles?",
"¿Te sientes atraído/a por la idea de trabajar en un entorno de laboratorio?",
"¿Te gusta estar al tanto de los avances científicos y tecnológicos más recientes?",
"¿Eres paciente y perseverante cuando enfrentas desafíos científicos y técnicos?",
"¿Te atrae la idea de trabajar en equipos multidisciplinarios que incluyan a científicos, ingenieros y profesionales de diversas áreas?",
"¿Te consideras una persona creativa con la capacidad de pensar de manera innovadora?",
"¿Te emociona la perspectiva de contribuir al desarrollo de tecnologías emergentes?",
"¿Tienes facilidad para entender y aplicar conceptos matemáticos avanzados?",
"¿Te gustaría trabajar en proyectos que tengan un impacto positivo en la sociedad a través de avances tecnológicos?"
 "",
"¿Disfrutas analizando y mejorando procesos para hacerlos más eficientes?",
"¿Te sientes atraído por la idea de diseñar sistemas que optimicen el uso de recursos en una empresa?",
"¿Prefieres trabajar en equipo para abordar problemas complejos en lugar de hacerlo de manera individual?",
"¿Te interesa entender cómo funcionan las cadenas de suministro y cómo se pueden optimizar?",
"¿Eres bueno identificando problemas y proponiendo soluciones prácticas?",
"¿Te gusta la idea de trabajar en entornos industriales y de manufactura?",
"¿Sientes curiosidad por la aplicación de la tecnología para mejorar los procesos productivos?",
"¿Tienes habilidades para la gestión y coordinación de proyectos?",
"¿Te atrae la idea de mejorar la seguridad en entornos laborales?",
"¿Eres capaz de pensar de manera estratégica y a largo plazo?",
"¿Te gustaría trabajar en la optimización de la cadena de distribución de productos?",
"¿Te sientes cómodo tomando decisiones basadas en análisis de datos?",
"¿Disfrutas resolviendo problemas logísticos y de distribución?",
"¿Tienes habilidades para la planificación y programación de tareas?",
"¿Te interesa implementar y mejorar sistemas de calidad en procesos industriales?",
"¿Te ves trabajando en la mejora continua de empresas y organizaciones?"

"¿Te interesan las aplicaciones prácticas de la química en la industria y la medicina?",
"¿Disfrutas resolviendo problemas complejos relacionados con la biología y la química?",
"¿Te gusta trabajar en un laboratorio, realizando experimentos y análisis?",
"¿Tienes curiosidad por entender cómo funcionan los procesos bioquímicos a nivel molecular?",
"¿Te atrae la idea de desarrollar nuevos medicamentos y tratamientos médicos?",
"¿Disfrutas de la investigación científica y la búsqueda de soluciones innovadoras?",
"¿Eres paciente y meticuloso/a al seguir procedimientos y protocolos experimentales?",
"¿Te interesa la ingeniería aplicada a la producción de alimentos y bebidas?",
"¿Te motiva la idea de contribuir al desarrollo de tecnologías sostenibles y respetuosas con el medio ambiente?",
"¿Te gusta trabajar en equipo para abordar desafíos científicos y tecnológicos?",
"¿Tienes habilidades para analizar y interpretar datos científicos de manera precisa?",
"¿Te sientes atraído/a por la idea de diseñar procesos para la producción de productos químicos y biomédicos?",
"¿Te gustaría trabajar en el diseño y optimización de sistemas de producción a nivel molecular?",
"¿Eres capaz de mantener la calma y tomar decisiones bajo presión en situaciones experimentales?",
"¿Te interesa la aplicación de la bioquímica en áreas como la biotecnología y la ingeniería genética?",
"¿Consideras importante la ética en la aplicación de la ingeniería bioquímica?"

"¿Te entusiasma la idea de trabajar en el desarrollo de tecnologías de la información?",
"¿Sientes interés por comprender cómo se transmiten y procesan los datos a través de redes?",
"¿Te atrae la posibilidad de diseñar y mantener sistemas informáticos para empresas?",
"¿Disfrutas explorando nuevas tecnologías y su aplicación en el ámbito empresarial?",
"¿Te gusta la idea de asegurar la seguridad y privacidad de la información en línea?",
"¿Eres curioso(a) acerca de cómo se diseñan y gestionan las redes de comunicación?",
"¿Te motiva la idea de desarrollar y mantener aplicaciones para dispositivos móviles?",
"¿Consideras importante la ciberseguridad y la protección contra amenazas digitales?",
"¿Te atrae la posibilidad de trabajar en el diseño y gestión de bases de datos?",
"¿Encuentras fascinante la inteligencia artificial y su aplicación en la resolución de problemas?",
"¿Te gustaría participar en el desarrollo de soluciones tecnológicas para empresas?",
"¿Te entusiasma la posibilidad de trabajar en proyectos de Internet de las cosas (IoT)?",
"¿Te resulta interesante la implementación de sistemas para mejorar la eficiencia empresarial?",
"¿Te preocupa la accesibilidad y usabilidad en el diseño de aplicaciones y sistemas?",
"¿Te emociona la idea de trabajar en el desarrollo de tecnologías de comunicación avanzadas?",
"¿Consideras importante la calidad y rendimiento en el diseño de sistemas de TIC?"
    
"¿Te apasiona el diseño y la planificación de espacios y edificios?",
"¿Disfrutas dibujando y creando representaciones visuales de ideas arquitectónicas?",
"¿Tienes una inclinación artística y apreciación por la estética?",
"¿Te gusta trabajar con materiales y conocer sus propiedades?",
"¿Eres meticuloso/a y cuidadoso/a con los detalles en tu trabajo?",
"¿Tienes habilidades para utilizar software de diseño arquitectónico?",
"¿Te sientes inspirado/a por la historia de la arquitectura y sus estilos?",
"¿Eres capaz de trabajar en equipos multidisciplinarios en proyectos de construcción?",
"¿Te interesa la sostenibilidad y el diseño ecológico en la arquitectura?",
"¿Tienes curiosidad por explorar la innovación en diseño y materiales?",
"¿Consideras importante la funcionalidad y la seguridad en los edificios que diseñas?",
"¿Te atrae la idea de trabajar en proyectos que mejoren la vida de las personas?",
"¿Te sientes cómodo/a realizando inspecciones en terreno y supervisando la construcción?",
"¿Eres una persona que disfruta aprendiendo sobre diseño urbano y paisajismo?",
"¿Te interesa el aspecto cultural y social de la arquitectura en las comunidades?",
"¿Estarías dispuesto/a a asumir responsabilidades adicionales para la excelencia en tus proyectos arquitectónicos?"

"¿Te apasiona la combinación de la ingeniería eléctrica y mecánica?",
"¿Disfrutas diseñando sistemas que involucran componentes eléctricos y mecánicos?",
"¿Tienes habilidades para trabajar con circuitos eléctricos y electrónica?",
"¿Te interesa la automatización de procesos industriales?",
"¿Eres meticuloso/a y cuidadoso/a con los detalles en tu trabajo?",
"¿Te gusta trabajar con máquinas y sistemas mecánicos?",
"¿Tienes la capacidad de diagnosticar y solucionar problemas eléctricos y mecánicos?",
"¿Te sientes cómodo/a utilizando software de diseño para sistemas electromecánicos?",
"¿Eres capaz de trabajar en equipos multidisciplinarios en proyectos de ingeniería?",
"¿Te interesa la gestión y mantenimiento de sistemas electromecánicos?",
"¿Consideras importante la eficiencia energética en sistemas electromecánicos?",
"¿Te atrae la idea de trabajar en la industria de la manufactura y producción?",
"¿Te sientes cómodo/a realizando pruebas y ensayos en sistemas electromecánicos?",
"¿Eres una persona que disfruta aprendiendo sobre control y automatización?",
"¿Te interesa la integración de sistemas electrónicos en maquinaria y equipos industriales?",
"¿Estarías dispuesto/a a asumir responsabilidades adicionales para asegurar el funcionamiento óptimo de sistemas electromecánicos?"


]

# Supongamos que estas son algunas carreras relacionadas con las preguntas
carreras_tec_tijuana = [
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "ingenieria-en-sistemas-computacionales",
 "Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
"Administración",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
 "Ingeniería Civil",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
  "Ingeniería Electrónica",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
    "Ingeniería en Logística",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
  "Contador Público",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
   "Ingeniería en Nanotecnología",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Industrial",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería Bioquímica",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Ingeniería en Tecnologías de la Información y Comunicación",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
    "Arquitectura",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",
  "Ingeniería Electromecánica",


    # ... (otras carreras) ...
    ]

caracteristicas_carrera ={
    "Administración": [
        "Desarrollo de estrategias de negocios innovadoras.",
        "Adaptabilidad a entornos empresariales cambiantes.",
        "Gestión eficiente de crisis y situaciones de emergencia.",
        "Análisis de tendencias y pronósticos de mercado.",
        "Desarrollo de relaciones estratégicas con clientes y socios.",
        "Utilización de tecnologías emergentes en gestión empresarial.",
        "Gestión de la diversidad y promoción de la inclusión.",
        "Desarrollo de planes de sucesión y liderazgo.",
        "Negociación efectiva en acuerdos comerciales.",
        "Aplicación de estrategias de responsabilidad social empresarial.",
        "Innovación en procesos de gestión y administración.",
        "Gestión de conflictos en el entorno laboral.",
        "Desarrollo de políticas de compensación y beneficios.",
        "Gestión de proyectos de expansión empresarial.",
        "Desarrollo de estrategias de retención de talento.",
        "Análisis de métricas y KPIs para la toma de decisiones.",
        "Gestión de equipos virtuales y trabajo remoto.",
        "Aplicación de metodologías ágiles en la gestión de proyectos.",
        "Desarrollo de planes de mercadotecnia y publicidad.",
        "Gestión de la innovación y fomento de la creatividad.",
        "Implementación de sistemas de gestión de calidad.",
        "Análisis de la competencia y benchmarking empresarial.",
        "Desarrollo de estrategias de fidelización de clientes.",
        "Gestión de crisis de reputación y relaciones públicas.",
        "Liderazgo en la transformación digital de la empresa.",
        "Gestión eficiente del tiempo y establecimiento de prioridades.",
        "Desarrollo de programas de capacitación y desarrollo.",
        "Gestión de proyectos de responsabilidad social empresarial.",
        "Gestión de la cadena de suministro de manera sostenible.",
        "Evaluación de la eficiencia operativa de la empresa.",
        "Desarrollo de estrategias de internacionalización.",
        "Gestión de la comunicación interna y externa de la empresa.",
        "Liderazgo en la implementación de sistemas ERP.",
        "Gestión de proyectos de transformación organizacional.",
        "Desarrollo de estrategias de pricing y análisis de costos.",
        "Gestión de crisis económicas y adaptación a recesiones.",
        "Desarrollo de estrategias de marketing digital.",
        "Gestión de la diversidad cultural en entornos globales."
        ],
    "Arquitectura": [
        "Innovación en diseño arquitectónico.",
        "Adaptación a nuevas tecnologías en construcción.",
        "Diseño de espacios públicos y recreativos.",
        "Gestión eficiente de recursos durante la construcción.",
        "Diseño sostenible y uso de energías renovables.",
        "Aplicación de principios de diseño bioclimático.",
        "Conocimiento profundo de la historia de la arquitectura.",
        "Colaboración con urbanistas y planificadores urbanos.",
        "Gestión de proyectos de restauración arquitectónica.",
        "Uso de herramientas avanzadas de visualización arquitectónica.",
        "Diseño de espacios interiores funcionales y estéticos.",
        "Integración de tecnologías inteligentes en el diseño.",
        "Gestión de proyectos de arquitectura de paisaje.",
        "Diseño de estructuras sismorresistentes y antisísmicas.",
        "Utilización de materiales reciclados y sostenibles.",
        "Investigación de nuevas tendencias en diseño arquitectónico.",
        "Diseño de edificios con enfoque en la accesibilidad.",
        "Gestión de proyectos de arquitectura eficiente en costos.",
        "Aplicación de técnicas de construcción modular.",
        "Diseño de espacios para el bienestar y la salud.",
        "Colaboración con ingenieros estructurales en proyectos.",
        "Desarrollo de proyectos de arquitectura eficientes en energía.",
        "Diseño de fachadas e iluminación arquitectónica.",
        "Colaboración con artistas en proyectos arquitectónicos.",
        "Gestión de proyectos arquitectónicos de alta complejidad.",
        "Diseño de proyectos arquitectónicos eficientes en agua.",
        "Utilización de tecnologías de construcción 3D.",
        "Diseño de proyectos de arquitectura corporativa.",
        "Gestión de proyectos arquitectónicos sustentables.",
        "Colaboración con comunidades locales en proyectos.",
        "Diseño de espacios para la creatividad y la innovación.",
        "Gestión de proyectos de arquitectura en entornos urbanos.",
        "Diseño de edificaciones resistentes a desastres naturales.",
        "Colaboración con arquitectos paisajistas en proyectos.",
        "Desarrollo de proyectos arquitectónicos con enfoque cultural.",
        "Diseño de espacios de aprendizaje innovadores.",
        "Gestión de proyectos arquitectónicos en áreas rurales.",
        "Aplicación de tecnologías de realidad aumentada en diseño.",
        "Diseño de proyectos arquitectónicos con enfoque comunitario."
        ],
    "Contador Público": [
        "Planificación financiera a corto y largo plazo.",
        "Análisis de tendencias económicas y financieras.",
        "Asesoramiento en fusiones y adquisiciones.",
        "Evaluación de riesgos empresariales.",
        "Implementación de sistemas de control interno.",
        "Desarrollo de estrategias de reducción de impuestos.",
        "Auditoría forense y detección de fraudes.",
        "Gestión de procesos de cumplimiento normativo.",
        "Utilización de tecnologías emergentes en contabilidad.",
        "Asesoramiento en inversiones y gestión patrimonial.",
        "Análisis de viabilidad financiera de proyectos.",
        "Desarrollo e implementación de políticas contables.",
        "Evaluación de impacto financiero de decisiones estratégicas.",
        "Colaboración con equipos multidisciplinarios en auditorías.",
        "Gestión de procesos de contabilidad internacional.",
        "Análisis de estados financieros para toma de decisiones.",
        "Desarrollo de estrategias de mitigación de riesgos.",
        "Evaluación de efectividad de controles financieros.",
        "Asesoramiento en transacciones financieras complejas.",
        "Análisis de costos para optimización de recursos.",
        "Gestión de procesos de auditoría interna y externa.",
        "Desarrollo de políticas de responsabilidad social corporativa.",
        "Aplicación de estándares internacionales de contabilidad.",
        "Gestión de procesos de informes financieros.",
        "Análisis de impacto financiero de cambios legislativos.",
        "Gestión de procesos de contabilidad gubernamental.",
        "Desarrollo de políticas de control de gastos.",
        "Auditoría de sistemas y seguridad de la información.",
        "Asesoramiento en procesos de reestructuración financiera.",
        "Gestión de procesos de contabilidad de costos.",
        "Desarrollo de políticas de gestión de efectivo.",
        "Análisis de rentabilidad de productos y servicios.",
        "Gestión de procesos de contabilidad de sociedades.",
        "Desarrollo de políticas de cumplimiento ético.",
        "Evaluación de impacto financiero de eventos extraordinarios.",
        "Gestión de procesos de contabilidad de pequeñas empresas.",
        "Desarrollo de políticas de gestión de deudas.",
        "Análisis de eficiencia de procesos contables.",
        "Gestión de procesos de contabilidad de entidades sin ánimo de lucro.",
        "Desarrollo de políticas de gestión de inventario.",
        "Análisis de eficacia de sistemas de información contable.",
        "Gestión de procesos de contabilidad de organizaciones internacionales.",
        "Desarrollo de políticas de gestión de activos fijos.",
        "Análisis de eficacia de procedimientos de auditoría.",
        "Gestión de procesos de contabilidad de entidades gubernamentales."
        ],
   "Ingeniería Bioquímica": [
        "Desarrollo de procesos de fermentación.",
        "Diseño y optimización de bioprocesos.",
        "Estudio de enzimas y catálisis en procesos biotecnológicos.",
        "Aplicación de técnicas de ingeniería metabólica.",
        "Diseño y operación de reactores biológicos.",
        "Análisis de expresión génica y proteómica.",
        "Producción y purificación de biomoléculas.",
        "Desarrollo de técnicas de clonación y expresión génica.",
        "Investigación en terapia génica y células madre.",
        "Diseño y desarrollo de fármacos biotecnológicos.",
        "Estudio de interacciones biomoleculares.",
        "Optimización de procesos de separación y purificación.",
        "Aplicación de nanotecnología en bioprocesos.",
        "Investigación en tecnologías emergentes en bioquímica.",
        "Desarrollo de biomateriales para aplicaciones médicas.",
        "Estudio de bioinformática y modelado molecular.",
        "Aplicación de técnicas de ingeniería de tejidos.",
        "Investigación en biología sintética.",
        "Desarrollo de terapias personalizadas.",
        "Aplicación de biotecnología en la producción de alimentos.",
        "Investigación en nanomedicina y entrega de medicamentos.",
        "Desarrollo de sistemas de liberación controlada de fármacos.",
        "Estudio de microbiología industrial.",
        "Investigación en bioprocesos sostenibles.",
        "Diseño de experimentos en ingeniería bioquímica.",
        "Aplicación de biotecnología en la producción de biocombustibles.",
        "Investigación en tecnologías de edición genética.",
        "Desarrollo de técnicas de diagnóstico molecular.",
        "Estudio de procesos de detoxificación ambiental.",
        "Investigación en biotecnología ambiental.",
        "Desarrollo de técnicas de bioingeniería.",
        "Aplicación de biotecnología en la industria textil.",
        "Investigación en bioquímica de alimentos.",
        "Desarrollo de sistemas de monitoreo en tiempo real de procesos biotecnológicos.",
        "Aplicación de inteligencia artificial en bioquímica.",
        "Investigación en metabolómica y análisis de metabolitos.",
        "Desarrollo de biosensores para detección de biomoléculas.",
        "Estudio de la interacción entre microbioma y salud humana.",
        "Investigación en terapia génica y edición de genes.",
        "Desarrollo de técnicas de inmunología molecular."
        ],
   "Ingeniería Civil": [
        "Optimización de diseño de estructuras de acero.",
        "Diseño de sistemas de drenaje pluvial.",
        "Análisis de riesgos sísmicos en estructuras.",
        "Gestión de proyectos de infraestructura urbana.",
        "Innovación en técnicas de construcción sostenible.",
        "Diseño y construcción de túneles y viaductos.",
        "Investigación en nuevos materiales de construcción.",
        "Diseño de sistemas de transporte público.",
        "Gestión de proyectos de rehabilitación urbana.",
        "Desarrollo de técnicas de construcción modular.",
        "Estudio de impacto social de proyectos de construcción.",
        "Investigación en sistemas de energías renovables aplicadas a la construcción.",
        "Diseño de sistemas de gestión de residuos de construcción.",
        "Gestión de proyectos de infraestructura de telecomunicaciones.",
        "Desarrollo de técnicas de construcción rápida y eficiente.",
        "Investigación en tecnologías de construcción 3D.",
        "Diseño y construcción de infraestructuras para energías renovables.",
        "Gestión de proyectos de construcción en entornos marinos.",
        "Investigación en construcción de infraestructuras resilientes al cambio climático.",
        "Diseño de sistemas de movilidad eléctrica.",
        "Gestión de proyectos de construcción con enfoque en la accesibilidad.",
        "Investigación en tecnologías de construcción con materiales reciclados.",
        "Diseño de sistemas de control de erosión en proyectos de construcción.",
        "Gestión de proyectos de construcción de parques urbanos.",
        "Investigación en sistemas de construcción antisísmica.",
        "Diseño de sistemas de iluminación eficiente en infraestructuras.",
        "Gestión de proyectos de construcción de instalaciones deportivas.",
        "Desarrollo de técnicas de construcción con impacto mínimo en el entorno.",
        "Investigación en técnicas de construcción para mitigar el impacto sonoro.",
        "Diseño y construcción de infraestructuras de almacenamiento de agua.",
        "Gestión de proyectos de construcción con enfoque en la biodiversidad.",
        "Investigación en técnicas de construcción para adaptarse al cambio climático.",
        "Diseño de sistemas de gestión de residuos industriales en proyectos de construcción.",
        "Gestión de proyectos de construcción con enfoque en la inclusividad.",
        "Investigación en tecnologías de construcción para la conservación del patrimonio histórico.",
        "Diseño y construcción de infraestructuras para la captura y reutilización de agua de lluvia.",
        "Gestión de proyectos de construcción en áreas de conservación ambiental.",
        "Investigación en tecnologías de construcción para la mitigación de la contaminación del suelo.",
        "Diseño de sistemas de construcción para la adaptación a fenómenos climáticos extremos."
        ],
  "Ingeniería Electromecánica": [
        "Desarrollo de sistemas de control para robots industriales.",
        "Investigación en tecnologías de energías renovables.",
        "Diseño y optimización de sistemas de generación de energía.",
        "Gestión de proyectos de instalación de sistemas solares.",
        "Estudio de tecnologías de almacenamiento de energía.",
        "Desarrollo de sistemas de automatización para la industria 4.0.",
        "Investigación en sistemas de conducción autónoma.",
        "Diseño de sistemas de monitorización de la salud de maquinaria industrial.",
        "Gestión de proyectos de sistemas de energía eólica.",
        "Estudio de tecnologías de vehículos eléctricos.",
        "Desarrollo de sistemas de control de calidad en procesos industriales.",
        "Investigación en tecnologías de inteligencia artificial aplicada a la producción.",
        "Diseño de sistemas de gestión de residuos industriales.",
        "Gestión de proyectos de instalación de sistemas de cogeneración.",
        "Estudio de tecnologías de motores eficientes y de bajo consumo.",
        "Desarrollo de sistemas de automatización para la agricultura de precisión.",
        "Investigación en tecnologías de realidad aumentada para mantenimiento industrial.",
        "Diseño de sistemas de gestión de la cadena de suministro.",
        "Gestión de proyectos de instalación de sistemas de energía hidráulica.",
        "Estudio de tecnologías de vehículos autónomos para logística.",
        "Desarrollo de sistemas de control para sistemas de transporte público.",
        "Investigación en tecnologías de reciclaje de equipos eléctricos y electrónicos.",
        "Diseño de sistemas de mantenimiento remoto de maquinaria industrial.",
        "Gestión de proyectos de instalación de sistemas de biomasa.",
        "Estudio de tecnologías de robótica colaborativa en entornos industriales.",
        "Desarrollo de sistemas de control para procesos de fabricación flexible.",
        "Investigación en tecnologías de energía mareomotriz.",
        "Diseño de sistemas de inspección automatizada en líneas de producción.",
        "Gestión de proyectos de instalación de sistemas de energía geotérmica.",
        "Estudio de tecnologías de realidad virtual para entrenamiento en mantenimiento industrial.",
        "Desarrollo de sistemas de control para sistemas de transporte de mercancías.",
        "Investigación en tecnologías de gestión de la calidad total.",
        "Diseño de sistemas de gestión de la seguridad industrial.",
        "Gestión de proyectos de instalación de sistemas de energía nuclear.",
        "Estudio de tecnologías de sistemas de gestión de flotas.",
        "Desarrollo de sistemas de control para sistemas de tratamiento de aguas industriales."
        ],
  "Ingeniería Electrónica": [
        "Diseño de circuitos integrados para aplicaciones específicas.",
        "Investigación en tecnologías de comunicación 6G.",
        "Desarrollo de sistemas de comunicación por satélite.",
        "Uso de sistemas de procesamiento de señales digitales avanzados.",
        "Diseño de sistemas de control para robots autónomos.",
        "Investigación en tecnologías de dispositivos cuánticos.",
        "Desarrollo de sistemas de procesamiento de imágenes médicas.",
        "Uso de tecnologías de inteligencia artificial para reconocimiento de patrones.",
        "Diseño de sistemas de interfaz cerebro-computadora.",
        "Investigación en tecnologías de sistemas de energía renovable integrados.",
        "Desarrollo de sistemas de comunicación para vehículos autónomos.",
        "Uso de tecnologías de electrónica flexible para dispositivos portátiles.",
        "Diseño de sistemas de control para vehículos aéreos no tripulados (drones).",
        "Investigación en tecnologías de electrónica bioinspirada.",
        "Desarrollo de sistemas de procesamiento de señales biomédicas.",
        "Uso de tecnologías de realidad aumentada en sistemas de visualización.",
        "Diseño de sistemas de sensores para monitoreo ambiental.",
        "Investigación en tecnologías de electrónica impresa.",
        "Desarrollo de sistemas de radar para aplicaciones de seguridad.",
        "Uso de tecnologías de electrónica cuántica para criptografía.",
        "Diseño de sistemas de control para sistemas de transporte inteligente.",
        "Investigación en tecnologías de electrónica de baja potencia.",
        "Desarrollo de sistemas de comunicación para Internet de las cosas (IoT).",
        "Uso de tecnologías de electrónica flexible en dispositivos médicos.",
        "Diseño de sistemas de control para sistemas de energía solar.",
        "Investigación en tecnologías de sensores infrarrojos.",
        "Desarrollo de sistemas de comunicación para redes neuronales.",
        "Uso de tecnologías de electrónica de potencia para sistemas de carga rápida.",
        "Diseño de sistemas de control para sistemas de almacenamiento de energía.",
        "Investigación en tecnologías de electrónica de radiofrecuencia.",
        "Desarrollo de sistemas de procesamiento de señales acústicas.",
        "Uso de tecnologías de electrónica transparente en dispositivos de visualización.",
        "Diseño de sistemas de control para sistemas de navegación autónoma.",
        "Investigación en tecnologías de electrónica de alta frecuencia.",
        "Desarrollo de sistemas de comunicación para sistemas de realidad virtual.",
        "Uso de tecnologías de electrónica de bajo consumo para dispositivos IoT.",
        "Diseño de sistemas de control para sistemas de seguridad biométrica.",
        "Investigación en tecnologías de electrónica para vehículos eléctricos.",
        "Desarrollo de sistemas de procesamiento de señales de radar."
        ],
   "Ingeniería en Gestión Empresarial": [
        "Implementación de estrategias de gestión del cambio.",
        "Análisis de tendencias del mercado y proyecciones empresariales.",
        "Desarrollo de estrategias de internacionalización de negocios.",
        "Gestión de la cadena de suministro global.",
        "Evaluación de la eficiencia operativa y recomendaciones de mejora.",
        "Implementación de sistemas de gestión de calidad total.",
        "Desarrollo de estrategias de responsabilidad social empresarial.",
        "Gestión de proyectos de transformación digital.",
        "Aplicación de técnicas de gestión de la innovación.",
        "Análisis de datos para la toma de decisiones estratégicas.",
        "Desarrollo de estrategias de marketing digital.",
        "Gestión de crisis y continuidad del negocio.",
        "Implementación de sistemas de gestión de relaciones con clientes (CRM).",
        "Desarrollo de estrategias de gestión de la información.",
        "Gestión de alianzas estratégicas y colaboraciones empresariales.",
        "Aplicación de técnicas de gestión de proyectos ágiles.",
        "Desarrollo de estrategias de gestión de talento.",
        "Gestión de la ciberseguridad en entornos empresariales.",
        "Análisis de la competencia y posicionamiento de mercado.",
        "Desarrollo de estrategias de gestión de la diversidad.",
        "Gestión de la cadena de suministro en entornos de crisis.",
        "Aplicación de técnicas de análisis de riesgos empresariales.",
        "Desarrollo de estrategias de gestión de la sostenibilidad.",
        "Gestión de la experiencia del cliente y fidelización.",
        "Análisis de costos y rentabilidad de proyectos empresariales.",
        "Desarrollo de estrategias de gestión de la marca.",
        "Gestión de proyectos de inteligencia empresarial (BI).",
        "Aplicación de técnicas de gestión de la cadena de valor.",
        "Desarrollo de estrategias de gestión de la calidad.",
        "Gestión de proyectos de implementación de sistemas ERP.",
        "Análisis de big data para la toma de decisiones empresariales.",
        "Desarrollo de estrategias de gestión de la logística.",
        "Gestión de proyectos de transformación organizacional.",
        "Aplicación de técnicas de gestión de la tecnología.",
        "Desarrollo de estrategias de gestión de la ética empresarial.",
        "Gestión de proyectos de desarrollo de productos y servicios.",
        "Análisis de datos para la optimización de procesos empresariales.",
        "Desarrollo de estrategias de gestión de la seguridad de la información.",
        "Gestión de proyectos de implementación de sistemas de CRM."
        ],
   "Ingeniería en Logística": [
       "Implementación de sistemas de gestión de transporte público.",
       "Gestión de flotas de vehículos comerciales.",
       "Desarrollo de estrategias de gestión de la cadena de frío.",
       "Análisis de la eficiencia energética en operaciones logísticas.",
       "Optimización de rutas de distribución de productos perecederos.",
       "Gestión de operaciones logísticas en entornos internacionales.",
       "Aplicación de tecnologías emergentes en la gestión de inventarios.",
       "Desarrollo de estrategias de logística inversa.",
       "Gestión de operaciones logísticas en entornos urbanos.",
       "Análisis de la viabilidad de la automatización en almacenes.",
       "Desarrollo de estrategias de gestión de devoluciones.",
       "Gestión de operaciones logísticas en entornos de comercio electrónico.",
       "Aplicación de técnicas de análisis de datos en operaciones logísticas.",
       "Desarrollo de estrategias de gestión de centros de distribución.",
       "Gestión de operaciones logísticas en la industria farmacéutica.",
       "Análisis de la sostenibilidad en el transporte de mercancías.",
       "Desarrollo de estrategias de gestión de la cadena de suministro farmacéutica.",
       "Gestión de operaciones logísticas en la industria de la moda.",
       "Aplicación de tecnologías de trazabilidad en la logística.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de alimentos.",
       "Gestión de operaciones logísticas en la industria de la tecnología.",
       "Análisis de la eficiencia en la distribución de productos electrónicos.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de productos tecnológicos.",
       "Gestión de operaciones logísticas en la industria automotriz.",
       "Aplicación de tecnologías de seguimiento en la logística de vehículos.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de repuestos automotrices.",
       "Gestión de operaciones logísticas en la industria de la construcción.",
       "Análisis de la eficiencia en la entrega de materiales de construcción.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de materiales de construcción.",
       "Gestión de operaciones logísticas en la industria química.",
       "Aplicación de protocolos de seguridad en el transporte de productos químicos.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de productos químicos.",
       "Gestión de operaciones logísticas en la industria del entretenimiento.",
       "Análisis de la eficiencia en la distribución de productos de entretenimiento.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de productos de entretenimiento.",
       "Gestión de operaciones logísticas en la industria del petróleo y gas.",
       "Aplicación de medidas de seguridad en el transporte de productos petrolíferos.",
       "Desarrollo de estrategias de gestión de la cadena de suministro de productos petrolíferos."
       ],
   "Ingeniería en Nanotecnología": [
       "Desarrollo de nanosensores para aplicaciones médicas.",
       "Investigación en nanomateriales para la mejora de la eficiencia energética.",
       "Aplicaciones en la industria textil para la creación de tejidos inteligentes.",
       "Diseño de nanodispositivos para la detección temprana de enfermedades.",
       "Aplicaciones de nanomateriales en la industria de la construcción.",
       "Investigación en nanotubos para el desarrollo de materiales ultrarresistentes.",
       "Desarrollo de nanomateriales para la purificación de agua.",
       "Aplicaciones de nanotecnología en la industria alimentaria.",
       "Investigación en nanocápsulas para la liberación controlada de fármacos.",
       "Diseño de nanosensores para la detección de contaminantes ambientales.",
       "Aplicaciones en la electrónica para el desarrollo de dispositivos más pequeños y eficientes.",
       "Investigación en nanomateriales para la generación de energía renovable.",
       "Desarrollo de nanotecnología en la medicina regenerativa.",
       "Aplicaciones de nanomateriales en la fabricación de pantallas flexibles.",
       "Investigación en nanobiosensores para la detección temprana de enfermedades.",
       "Diseño de nanorobots para aplicaciones médicas.",
       "Aplicaciones de nanotecnología en la industria aeroespacial.",
       "Investigación en nanomateriales para la fabricación de baterías más eficientes.",
       "Desarrollo de nanosensores para la monitorización de estructuras.",
       "Aplicaciones de nanomateriales en la industria de la cosmética.",
       "Investigación en nanotubos para la creación de materiales ligeros y resistentes.",
       "Diseño de nanosensores para la detección de gases tóxicos.",
       "Aplicaciones de nanotecnología en la fabricación de dispositivos médicos.",
       "Investigación en nanomateriales para la fabricación de supercondensadores.",
       "Desarrollo de nanosensores para la detección de biomarcadores.",
       "Aplicaciones de nanotecnología en la fabricación de circuitos integrados.",
       "Investigación en nanomateriales para la purificación del aire.",
       "Diseño de nanosensores para la monitorización de variables ambientales.",
       "Aplicaciones de nanotecnología en la industria del petróleo y gas.",
       "Investigación en nanomateriales para la creación de materiales autoreparables.",
       "Desarrollo de nanosensores para la detección de patógenos.",
       "Aplicaciones de nanotecnología en la fabricación de materiales hidrofóbicos.",
       "Investigación en nanomateriales para la fabricación de dispositivos cuánticos.",
       "Diseño de nanosensores para la detección de metales pesados.",
       "Aplicaciones de nanotecnología en la fabricación de materiales autorreproducibles.",
       "Investigación en nanomateriales para la fabricación de nanofibras.",
       "Desarrollo de nanosensores para la monitorización de la calidad del suelo.",
       "Aplicaciones de nanotecnología en la fabricación de materiales autolubricantes.",
       "Investigación en nanomateriales para la fabricación de nanosatélites."
       ],
   "Ingeniería en Sistemas Computacionales": [
       "Implementación de sistemas de inteligencia artificial.",
       "Desarrollo de algoritmos de aprendizaje automático.",
       "Optimización de código y rendimiento de software.",
       "Diseño de arquitecturas de sistemas distribuidos.",
       "Gestión de bases de datos distribuidas y NoSQL.",
       "Desarrollo de sistemas de realidad virtual y aumentada.",
       "Implementación de soluciones de ciberseguridad avanzadas.",
       "Programación en entornos de desarrollo integrados (IDE).",
       "Desarrollo de aplicaciones para dispositivos IoT.",
       "Diseño e implementación de sistemas embebidos.",
       "Gestión de proyectos de desarrollo de software.",
       "Análisis de impacto y riesgo en proyectos de software.",
       "Colaboración en proyectos de código abierto.",
       "Uso de frameworks y bibliotecas de desarrollo.",
       "Desarrollo de interfaces de usuario accesibles.",
       "Implementación de sistemas de gestión de versiones (VCS).",
       "Diseño e implementación de arquitecturas de microservicios.",
       "Resolución de problemas de escalabilidad en sistemas.",
       "Evaluación y selección de tecnologías emergentes.",
       "Participación en comunidades y eventos tecnológicos."
       ],
   "Ingeniería en Tecnologías de la Información y Comunicación": [
       "Desarrollo de software orientado a la inteligencia artificial.",
       "Gestión de grandes volúmenes de datos (Big Data).",
       "Desarrollo de sistemas de realidad virtual y aumentada.",
       "Seguridad en la gestión de identidad y acceso.",
       "Desarrollo de aplicaciones para dispositivos móviles.",
       "Integración de tecnologías emergentes en entornos empresariales.",
       "Análisis predictivo y modelado de datos.",
       "Desarrollo de soluciones para la Internet de las cosas (IoT).",
       "Gestión de servicios de tecnologías de la información.",
       "Desarrollo de estrategias de transformación digital.",
       "Aplicaciones de blockchain en entornos empresariales.",
       "Desarrollo de sistemas de gestión de contenidos (CMS).",
       "Gestión de proyectos de implementación de sistemas.",
       "Desarrollo de interfaces de usuario intuitivas.",
       "Análisis forense en casos de ciberseguridad.",
       "Gestión de redes y sistemas de comunicación.",
       "Desarrollo de protocolos de seguridad informática.",
       "Innovación en sistemas de comunicación móvil 5G.",
       "Evaluación y selección de tecnologías emergentes.",
       "Desarrollo de estrategias de ciberresiliencia."
       ],
   "Ingeniería Industrial": [
       "Diseño de sistemas de producción flexibles.",
       "Gestión de la cadena de suministro global.",
       "Implementación de tecnologías IoT en procesos industriales.",
       "Desarrollo de estrategias para la sostenibilidad industrial.",
       "Aplicación de Lean Manufacturing en entornos de producción.",
       "Diseño de almacenes automatizados.",
       "Optimización de procesos logísticos mediante simulación.",
       "Gestión de la cadena de suministro en entornos de comercio electrónico.",
       "Implementación de sistemas de manufactura aditiva (impresión 3D).",
       "Colaboración en proyectos de Industria 4.0.",
       "Desarrollo de estrategias para la mejora de la eficiencia energética.",
       "Implementación de sistemas de gestión de energía en entornos industriales.",
       "Gestión de la seguridad industrial y prevención de riesgos laborales.",
       "Desarrollo de soluciones para la automatización de procesos de fabricación.",
       "Análisis de datos para la toma de decisiones en operaciones industriales.",
       "Diseño y optimización de sistemas de embalaje y etiquetado.",
       "Gestión de proyectos de inversión en infraestructuras industriales.",
       "Desarrollo de estrategias para la reutilización de residuos industriales.",
       "Implementación de sistemas de mantenimiento predictivo en maquinaria industrial.",
       "Colaboración en proyectos de eficiencia hídrica en operaciones industriales.",
       "Diseño de sistemas de gestión de la innovación en entornos industriales.",
       "Gestión de la responsabilidad social corporativa en empresas industriales.",
       "Desarrollo de estrategias para la mejora de la productividad laboral.",
       "Implementación de sistemas de gestión de la calidad en procesos industriales.",
       "Gestión de la logística inversa y el reciclaje de productos industriales.",
       "Colaboración en proyectos de fabricación personalizada (manufactura aditiva).",
       "Desarrollo de estrategias para la adaptación a cambios en la demanda del mercado.",
       "Implementación de sistemas de gestión de la información en operaciones industriales.",
       "Gestión de proyectos de automatización de almacenes y centros de distribución.",
       "Diseño y optimización de sistemas de transporte interno en entornos industriales.",
       "Colaboración en proyectos de ergonomía y bienestar laboral en entornos industriales.",
       "Desarrollo de estrategias para la mejora de la eficiencia de procesos de empaque.",
       "Implementación de sistemas de gestión de la cadena de frío en operaciones industriales.",
       "Gestión de proyectos de implementación de sistemas de realidad aumentada en entornos industriales.",
       "Diseño y optimización de sistemas de gestión de inventarios y almacenes.",
       "Colaboración en proyectos de implementación de sistemas de inteligencia artificial en procesos industriales.",
       "Desarrollo de estrategias para la adaptación de procesos industriales a normativas ambientales.",
       "Implementación de sistemas de gestión de la cadena de suministro basados en tecnologías blockchain.",
       "Gestión de proyectos de implementación de sistemas de fabricación flexible."
       ]
}

# Cargar respuestas de usuario desde un archivo de texto
ruta_respuestas_usuario = os.path.join(carpeta_retroalimentacion, 'respuestas_usuario.txt')

try:
    with open(ruta_respuestas_usuario, 'r', encoding='utf-8') as file:
        respuestas_usuario = file.read().splitlines()
except FileNotFoundError:
    print(f"El archivo '{ruta_respuestas_usuario}' no se encontró.")
    respuestas_usuario = []
except Exception as e:
    print(f"Se produjo un error al abrir el archivo: {str(e)}")

# Verificar que la longitud de preguntas y respuestas_usuario sea la misma
if len(preguntas) != len(respuestas_usuario):
    print("El número de respuestas proporcionadas no coincide con el número de preguntas.")
    print(len(respuestas_usuario))
    print(len(preguntas))
else:
    # Inicializar el TfidfVectorizer
    vectorizer = TfidfVectorizer()

    # Calcular la similitud entre las respuestas del usuario y las características de carrera
    nuevas_respuestas_tfidf = vectorizer.fit_transform(respuestas_usuario)

    similitud_carreras = {}
    for carrera, caracteristicas in caracteristicas_carrera.items():
        similitud = cosine_similarity(nuevas_respuestas_tfidf, vectorizer.transform(caracteristicas))
        similitud_carreras[carrera] = similitud.mean()

    # Ordenar las carreras por similitud en orden descendente
    carreras_recomendadas = sorted(similitud_carreras.items(), key=lambda x: x[1], reverse=True)

    # Define la ruta de la carpeta para la retroalimentación
    carpeta_resultados = 'resultados'

    # Asegúrate de que la carpeta exista; si no, créala
    if not os.path.exists(carpeta_resultados):
        os.makedirs(carpeta_resultados)
        
    # Nombre base del archivo
    nombre_base = "resultados.txt"
    
    # Verifica si el archivo ya existe
    contador = 1
    ruta_archivo = os.path.join(carpeta_resultados, nombre_base)
    
    while os.path.exists(ruta_archivo):
        # Si ya existe, crea un nuevo nombre con un número incremental
        nombre_base = f"resultados_{contador}.txt"
        ruta_archivo = os.path.join(carpeta_resultados, nombre_base)
        contador += 1

    # Mostrar las carreras recomendadas
    with open(ruta_archivo, 'w') as archivo:
        print("\nCarreras recomendadas:\n")
        resultado_str = "Carreras recomendadas:\n\n"
        archivo.write(resultado_str)
        for carrera, similitud_porcentaje in carreras_recomendadas:
            similitud_porcentaje *= 100
            print(f"{carrera} - Similitud: {similitud_porcentaje:.2f}%")
            resultado_str2 = f"{carrera} - Similitud: {similitud_porcentaje:.2f}%\n"
            # Guardar el contenido en el archivo
            archivo.write(resultado_str2)
    
    
        